### ISSUE TITLE
Change the way the home folder is moved to /replicated

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/mws-panel#127]
To avoid the error message from ansible that the home folder is busy. Example of the error in the comments

**Comment by abrahammartin** [comment]
➤ Abraham Martin commented:

TASK [mwsclient-stretch : migrate items to /replicated] ************************
changed: [mws-priv-23.mws3.csx.cam.ac.uk] => (item=/var/lib/mysql)
changed: [mws-priv-23.mws3.csx.cam.ac.uk] => (item=/var/www)
failed: [mws-priv-23.mws3.csx.cam.ac.uk] (item=/home) => {"changed": true, "cmd": ["mv", "/home", "/replicated/home"], "delta": "0:00:00.009985", "end": "2017-12-18 21:25:16.469480", "failed": true, "item": "/home", "rc": 1, "start": "2017-12-18 21:25:16.459495", "stderr": "mv: cannot remove '/home': Device or resource busy", "stdout": "", "stdout_lines": [], "warnings": []}
changed: [mws-priv-23.mws3.csx.cam.ac.uk] => (item=/var/spool)

**Comment by ph448** [comment]
This has been fixed in uisautomation/mws-ansible#201 as far as I can tell.
