### ISSUE TITLE
Creation of test VM does not complete for VMs with certificate

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/mws-panel#173]
The creation of tests VMs was suspended early August as users were not able to have a proper test VM created. Quick investigation seems to show that Ansible and the copy of the files are happening in the inverse order.

**Comment by abrahammartin** [comment]
@ph448 needs to split this issue into the issues he's found. This issue will be closed once the new issues are written.

**Comment by ph448** [comment]
This has been split into uisautomation/mws-ansible#173, uisautomation/mws-ansible#174 and uisautomation/mws-ansible#175.
