### ISSUE TITLE
MW350 Need additional warnings around MySQL root password reset

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/mws-panel#67]
Terry Chilvers <tc256@cam.ac.uk>

On the MWS control panel, there is an option to change the MWS root password. However, clicking this appears to immediately change the mysql root password to a temporary one without any prompts or warnings, with an option to cancel. I think this is an oversight and there should really be a prompt to warn the user before changing anything. Having clicked this I now need to go and reset the root password, something I didn’t really want to do at this time.

**Comment by ph448** [comment]
Stretch does not use this any more, no fix planned for jessie.
